### ISSUE TITLE
Tag FDA-approved drugs

### ISSUE THREAD

**Issue by jgoecks** [ohsu-comp-bio/g2p-aggregator#36] opened 2017-07-12 23:14 UTC
It would be great to tag drugs as FDA approved, perhaps using Orange Book: https://www.accessdata.fda.gov/scripts/cder/ob/

**Comment by bwalsh** [comment] 2017-07-13 02:14
Is this a duplicate of the evidence_level normalization in place?
https://docs.google.com/spreadsheets/d/1j9AKdv1k87iO8qH-ujnW3x4VusbGoXDjdb5apUqJsSI/edit#gid=613354436

**Comment by jgoecks** [comment] 2017-07-13 03:56
Not a duplicate: this is about annotating drugs as FDA-approved, not about the evidence-level being an FDA guideline.

**Comment by bwalsh** [comment] 2017-08-01 00:01
evironmentalContexts now return an `approved_countries` array

```
{
  "term": "Imatinib",
  "description": "Imatinib",
  "taxonomy": {
    "kingdom": "Organic compounds",
    "direct-parent": "N-phenylbenzamides",
    "class": "Benzene and substituted derivatives",
    "subclass": "Benzamides",
    "superclass": "Benzenoids"
  },
  "usan_stem": "tyrosine kinase inhibitors",
  "toxicity": "The most frequently reported adverse reactions (>30%) were edema, nausea,\r\nvomiting, muscle cramps, musculoskeletal pain, diarrhea, rash, fatigue and\r\nabdominal pain.",
  "approved_countries": [
    "Canada",
    "US"
  ],
  "id": "compound:CID5291"
}
```

@jgoecks   can you review

**Closed as completed** 2017-08-22 23:39 UTC
